### ISSUE TITLE
6/27/2019 meeting

### ISSUE THREAD

**Issue by stellasylee** [stellasylee/STA499#1]
- [x] function for find time frame for control and experiment for first secondary task
- [x] find sd of lane deviation for each segment
- [x] find average and change in speed for each segment
- [x] create x of our dataframe for analysis (ID, dosing condition, control/experiment)
- [x] create y of dataframe: sd of lane deviation, speed variables

**Comment by IshaanTibrewal** [comment]
We should also look at deviation from speed limit for control and experimental group

**Comment by stellasylee** [comment]
- [x] change point detection for engagement point

**Comment by stellasylee** [comment]
- [x] update csv files for including dosing levels

**Comment by IshaanTibrewal** [comment]
- [x] Find sd of speed (wait for Prof. Miller to clarify on sd of mean speed)

**Comment by stellasylee** [comment]
- [x] explore 3 artist tasks
- [x] including side mirror task?

**Comment by stellasylee** [comment]
- [x] try changing time frame (start - end, not engage-end)
